services:
  app:
    build: .
    container_name: colordays_app
    ports:
      # Note: If you change PORT in backend/config.py, you must also change it here!
      - "8000:8000"
    volumes:
      - ./backend/data:/app/backend/data
    restart: unless-stopped
